language: node_js

node_js:
  - "10.15"
  - "7.8"
  - "6.9"
  - "5.1"
  - "4.2"
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install python-software-properties -qq
  - sudo apt-add-repository ppa:ondrej/php7 -y
  - sudo apt-get update -qq
  - sudo apt-get install php7 -qq
  - sudo apt-get install php7-sqlite -qq
  - php -v
  - php -r "readfile('https://getcomposer.org/installer');" | php

before_script:
  - php composer.phar install
  - npm install

script:
  - npm test

notifications:
  emails:
    - tomk79@gmail.com
  on_success: always
  on_failure: always
