language: node_js

node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"

before_script:
  - npm install
  - php -v

script:
  - npm test

notifications:
  emails:
    - tomk79@gmail.com
  on_success: always
  on_failure: always
