language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
  - "iojs"
  - "iojs-v1.0.4" 

php:
  - "5.6"
  - "5.5"
  - "5.4"

before_install:
  - composer selfupdate

before_script:
  - composer install
  - npm install

script:
  - npm test

notifications:
  emails:
    - tomk79@gmail.com
  on_success: always
  on_failure: always
